plpy.SPIError: column "badcolumnnamex" does not exist (plpython.c:4648)