-- @description Input tests for Sumary
-- @madlib-param target_cols = "NULL"
-- @madlib-param grouping_cols = "'-1'"
-- @madlib-param ntile_array = "NULL"
-- @madlib-param tbl_output = "'_mdadlib_input_test_summary_output_'"
-- @madlib-param get_quartiles = "True"
-- @madlib-param get_estimates = "True"
-- @madlib-param dataset = "'madlibtestdata.dt_golf'"
-- @madlib-param get_distinct = "True"
          set client_min_messages to error;
SET
          select * from
          madlib.summary(
              'madlibtestdata.dt_golf',
              '_mdadlib_input_test_summary_output_',
              NULL,
              '-1',
              True,
              True,
              NULL,
              10,
              True
          );
psql:/Users/iyerr3/Work/MADlib/tinc/tinc/tincrepo/madlib/tests/Summary/sql_SummaryInputTestCase/test_summary_input_test_5.sql:24: ERROR:  plpy.Error: (plpython.c:4648)
DETAIL:  Summary -- Invalid paramter: column(s) "-1" missing from source table
CONTEXT:  Traceback (most recent call last):
  PL/Python function "summary", line 27, in <module>
    get_distinct, get_quartiles, ntile_array, how_many_mfv, get_estimates)
  PL/Python function "summary", line 72, in summary
  PL/Python function "summary", line 369, in run
  PL/Python function "summary", line 124, in _validate_paras
  PL/Python function "summary", line 80, in _validate_grouping_cols
PL/Python function "summary"
              
