-- @description This is for output tests of correlation.
-- @madlib-param target_cols = "'humidity, temperature'"
-- @madlib-param tbl_output = "NULL"
-- @madlib-param dataset = "'madlibtestdata.non_existing_table'"
          set client_min_messages to error;
SET
          select output_table, row_count from
          madlib.correlation(
              'madlibtestdata.non_existing_table',
              NULL,
              'humidity, temperature');
psql:/Users/qianh1/workspace/madlib_testsuite/tests/Correlation/sql_input/test_correlation_input_test_23.sql:12: ERROR:  plpy.Error: Correlation error:  Relation 'madlibtestdata.non_existing_table' does not exist (plpython.c:4648)
CONTEXT:  Traceback (most recent call last):
  PL/Python function "correlation", line 25, in <module>
    return correlation.correlation(schema_madlib, source_table, output_table, target_cols)
  PL/Python function "correlation", line 28, in correlation
  PL/Python function "correlation", line 92, in _validate_corr_arg
PL/Python function "correlation"
          
